<?php

/**
 * Implements hook_theme().
 */
function angular_chart_theme($existing, $type, $theme, $path) {
  return array(
    'angular_chart' => array(
      'render element' => 'elements',
    ),
    'bar_chart' => array(
      'render element' => 'elements',
    ),
    'doughnut_chart' => array(
      'render element' => 'elements',
    ),
  );
}

/**
 * Implements hook_page_attachments().
 */
function angular_chart_page_attachments(array &$attachments) {
  $attachments['#attached']['library'][] = 'angular_chart/drupal.angular_chart';
}
